import { ICatFood } from "./interface";

export const catFoods: ICatFood[] = [
    {
        title: 'Сказачное заморское яство',
        alttitle: '',
        name: 'Нямушка',
        contain: 'с фуа-гра',
        count: 10,
        gift: 1,
        weight: '0,5',
        footer: 'Чего сидишь? Порадуй котэ, ',
        altfooter: 'Печень утки разварная с артишоками.',
        a: 'купи.',
        disabled: false,
    },
    {
        title: 'Сказачное заморское яство',
        alttitle: '',
        name: 'Нямушка',
        contain: 'с рыбой',
        count: 40,
        gift: 2,
        weight: '2',
        footer: 'Чего сидишь? Порадуй котэ, ',
        altfooter: 'Головы щучьи с чесночком да свежайщая сёмгушка',
        a: 'купи.',
        disabled: false,
    },
    {
        title: 'Сказачное заморское яство',
        alttitle: '',
        name: 'Нямушка',
        contain: 'с курой',
        count: 100,
        gift: 5,
        weight: '5',
        footer: 'Чего сидишь? Порадуй котэ, ',
        altfooter: 'Филе из циплят с трюфелями в бульоне',
        a: 'купи.',
        disabled: true,
    },
]